#pragma once

//Threshold values for DEBUG
//#define ABSOLUTE_ANGULAR_THRESHOLD 50
//#define ABSOLUTE_ACCELERATION_THRESHOLD 100
//#define ABSOLUTE_AMBIENT_THRESHOLD 100
//#define ABSOLUTE_MICROPHONE_THRESHOLD 100

//real values
#define ABSOLUTE_ANGULAR_THRESHOLD 0.8
#define ABSOLUTE_ACCELERATION_THRESHOLD 10
#define ABSOLUTE_AMBIENT_THRESHOLD 3.5
#define ABSOLUTE_MICROPHONE_THRESHOLD 4

#define WAIT_SECONDS_BEFORE_ARMING 10

// Read and evaluate sensors every seconds&nanoseconds
#define READ_SENSORS_EVERY_SECONDS 1
#define READ_SENSORS_EVERY_NANO_SECONDS 0

//constants

#define SCOPEID_LENGTH 20
#define JSON_BUFFER_SIZE 128
#define MT3620_ADC_CHANNEL0 (0)
#define ALS_PT19_MAX_VOLTAGE 2.5
#define MICROPHONE_MAX_VOLTAGE 2.5
